### ISSUE TITLE
Broken on neovim 0.1.7

### ISSUE THREAD

**Issue by optixx** [zhamlin/tiler.vim#4]
I get this when i  open a 2nd window via :TilerNew

```
Error detected while processing function tiler#create_window[5]..tiler#reorder[99]..<SNR>98_resize_master[30]..<SNR>98_window_resize_percentage[2]..<SNR>98_winmaxheight:
line    4:
E117: Unknown function: gettabinfo
E116: Invalid arguments for function len(gettabinfo()) > 1 && &showtabline
E15: Invalid expression: len(gettabinfo()) > 1 && &showtabline
```

**Comment by zhamlin** [comment]
Looks like `gettabinfo` was introduced in [vim 7.4.2204](https://github.com/vim/vim/commit/b5ae48e9ffd3b8eb6ca4057de11f1bddcde8ce6f). What does `echo tabpagenr()` display for you? If that works, I'll update the code to use that.

**Comment by optixx** [comment]
Yep, it works.
